# Generated by Django 5.0.3 on 2024-03-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='phone_field',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='user',
            new_name='username',
        ),
    ]
