# Generated by Django 5.0.3 on 2024-03-11 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0004_rename_phone_field_employe_phonenumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Users',
        ),
    ]
